# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password1', models.CharField(max_length=128, verbose_name='密码')),
                ('password2', models.CharField(max_length=128, verbose_name='密码确认')),
                ('tel', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('headshot', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar/%Y/%m/%d', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password1', models.CharField(max_length=128, verbose_name='密码')),
                ('password2', models.CharField(max_length=128, verbose_name='密码确认')),
                ('tel', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门')),
            ],
        ),
    ]
