# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zhaopin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='招聘要求')),
                ('peopleNumber', models.IntegerField(verbose_name='人数')),
                ('publishTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(default='管理员', on_delete=django.db.models.deletion.CASCADE, to='users.Recruiter', verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhaopin.Category', verbose_name='类别')),
                ('workLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhaopin.WorkLocation', verbose_name='工作地点')),
            ],
        ),
    ]
